
version: "3.9"
services:
  catalog-db:
    image: mongo:latest
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    ports:
      - '8094:27017'
  auth:
    image: node:16.13.2-alpine
    volumes:
      - .:/app
    ports:
      - '3001:3001'
      - '9229:9229'
    depends_on:
      - catalog-db
    environment:
      NODE_ENV: 'test'
      API_HOST: '0.0.0.0'
      API_PORT: '3001'
      API_ENABLE_LOG: 'true'
      DB_URI: 'mongodb://catalog-db:27017/catalog_db'
