version: "3.9"
services:
  auth:
    image: node:16.13.2-alpine
    volumes:
      - .:/app
    ports:
      - '3001:3001'
      - '9229:9229'
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      API_HOST: 0.0.0.0
      API_PORT: 3001
  mongo:
    image: mongo:latest
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
